# Generated by Django 4.1.7 on 2023-03-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsType',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'jobstype',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_card_no', models.BigIntegerField()),
                ('card_cvv', models.IntegerField()),
                ('card_name', models.CharField(max_length=250)),
                ('card_validity', models.DateTimeField()),
                ('card_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_middle_name', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_password', models.CharField(max_length=550)),
                ('create_at', models.DateTimeField()),
                ('current_location_lat', models.FloatField(null=True)),
                ('current_location_long', models.FloatField(null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('user_is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_created_at', models.DateTimeField(auto_created=True)),
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('client', 'client'), ('employee', 'employee')], max_length=50)),
                ('role_module', models.CharField(max_length=100, null=True)),
                ('role_permission', models.CharField(max_length=100, null=True)),
                ('role_status', models.BooleanField()),
                ('role_is_delete', models.BooleanField(default=0)),
                ('role_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userrole',
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_details', models.CharField(max_length=200)),
                ('vehicle_modification', models.CharField(max_length=200, null=True)),
                ('vehicle_license', models.FileField(blank=True, null=True, upload_to='licenses')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('vehicle_status', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_user_email', models.EmailField(max_length=254)),
                ('session_token', models.CharField(max_length=150, unique=True)),
                ('session_exp', models.DateTimeField()),
                ('session_status', models.BooleanField()),
                ('session_created_at', models.DateTimeField()),
                ('session_updated_at', models.DateTimeField(null=True)),
                ('session_is_delete', models.BooleanField(default=1)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.userrole'),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_location_lat', models.FloatField()),
                ('current_location_long', models.FloatField()),
                ('vehicle_details', models.CharField(max_length=300)),
                ('vehicle_modification', models.CharField(max_length=400)),
                ('vehicle_license', models.FileField(upload_to='licenses')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('job_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openup_app.jobstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'userjob',
            },
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('forgot_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('token', models.CharField(max_length=300)),
                ('timestamp', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'forgot_password',
            },
        ),
    ]
