# Generated by Django 4.1.7 on 2023-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_middle_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_number', models.CharField(max_length=12)),
                ('user_password', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('user_is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
    ]
