# Generated by Django 4.1.7 on 2023-03-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('service', 'service'), ('emergency', 'emergency')], default='service', max_length=20),
        ),
    ]
