# Generated by Django 4.1.7 on 2023-03-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0002_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.jobstype'),
        ),
    ]
