# Generated by Django 4.1.7 on 2023-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0002_alter_registration_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='update_at',
            field=models.DateTimeField(),
        ),
    ]
