# Generated by Django 4.1.7 on 2023-03-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0003_alter_jobs_job_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='current_location_lat',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='current_location_long',
            new_name='location_longitude',
        ),
    ]
