# Generated by Django 4.1.7 on 2023-03-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0003_alter_registration_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
