# Generated by Django 4.1.7 on 2023-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0004_remove_vehicledetails_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
