# Generated by Django 4.1.7 on 2023-03-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0004_alter_registration_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_user_email', models.EmailField(max_length=254)),
                ('session_token', models.CharField(max_length=150, unique=True)),
                ('session_exp', models.DateTimeField()),
                ('session_status', models.BooleanField()),
                ('session_created_at', models.DateTimeField()),
                ('session_updated_at', models.DateTimeField(null=True)),
                ('session_is_delete', models.BooleanField(default=1)),
                ('session_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
    ]
