# Generated by Django 4.1.7 on 2023-03-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0004_rename_current_location_lat_jobs_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='current_location_lat',
            new_name='location_latitude',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='current_location_long',
            new_name='location_longitude',
        ),
    ]
