# Generated by Django 4.1.7 on 2023-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0005_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_password',
            field=models.CharField(max_length=550),
        ),
    ]
