# Generated by Django 4.1.7 on 2023-03-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0005_rename_current_location_lat_registration_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('screen', models.BooleanField(default=1)),
                ('only_using', models.BooleanField(default=1)),
                ('service_not', models.BooleanField(default=1)),
                ('location_not', models.BooleanField(default=1)),
                ('ser_feed_not', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'user_setting',
            },
        ),
    ]
