# Generated by Django 4.1.7 on 2023-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0006_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='location',
            field=models.BooleanField(default=1),
        ),
    ]
