# Generated by Django 4.1.7 on 2023-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0007_settings_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_accepted_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
