# Generated by Django 4.1.7 on 2023-03-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0007_forgotpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_created_at', models.DateTimeField(auto_created=True)),
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('client', 'client'), ('employee', 'employee')], max_length=50)),
                ('role_module', models.CharField(max_length=100, null=True)),
                ('role_permission', models.CharField(max_length=100, null=True)),
                ('role_status', models.BooleanField()),
                ('role_is_delete', models.BooleanField(default=0)),
                ('role_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userrole',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.userrole'),
        ),
    ]
