# Generated by Django 4.1.7 on 2023-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0008_userrole_registration_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_phone_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
