# Generated by Django 4.1.7 on 2023-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0008_jobs_job_accepted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_accepted_by',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
