# Generated by Django 4.1.7 on 2023-03-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0009_alter_registration_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_details', models.TextField(max_length=200)),
                ('vehicle_license', models.ImageField(upload_to='licenses')),
                ('vehicle_license_after', models.ImageField(blank=True, null=True, upload_to='licenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'vehicle_model',
            },
        ),
    ]
