# Generated by Django 4.1.7 on 2023-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0009_alter_jobs_job_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_status',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
