# Generated by Django 4.1.7 on 2023-03-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0010_alter_registration_user_phone_number_vehicledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='vehicle_modification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_details',
            field=models.CharField(max_length=200),
        ),
    ]
