# Generated by Django 4.1.7 on 2023-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0010_registration_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='device_type',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
