# Generated by Django 4.1.7 on 2023-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0011_registration_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_fcm_token',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_last_name',
            field=models.CharField(max_length=150),
        ),
    ]
