# Generated by Django 4.1.7 on 2023-03-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0011_vehicledetails_vehicle_modification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle_license_after',
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_license',
            field=models.ImageField(blank=True, null=True, upload_to='licenses'),
        ),
    ]
