# Generated by Django 4.1.7 on 2023-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0012_remove_vehicledetails_vehicle_license_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_license',
            field=models.FileField(blank=True, null=True, upload_to='licenses'),
        ),
    ]
