# Generated by Django 4.1.7 on 2023-03-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0012_registration_user_fcm_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_card_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
