# Generated by Django 4.1.7 on 2023-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0013_payment_user_alter_payment_user_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_card_no',
            field=models.BigIntegerField(),
        ),
    ]
