# Generated by Django 4.1.7 on 2023-03-09 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0013_alter_vehicledetails_vehicle_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 12, 16, 48, 844441)),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vehicle_status',
            field=models.BooleanField(default=0),
        ),
    ]
