# Generated by Django 4.1.7 on 2023-03-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0014_alter_payment_user_card_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='users',
        ),
    ]
