# Generated by Django 4.1.7 on 2023-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0014_vehicledetails_created_at_vehicledetails_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetails',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
