# Generated by Django 4.1.7 on 2023-03-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0015_alter_registration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_users', models.CharField(max_length=500)),
                ('alert_title', models.CharField(max_length=500)),
                ('alert_messages', models.CharField(max_length=500)),
                ('alert_status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('alert_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.jobs')),
            ],
        ),
    ]
