# Generated by Django 4.1.7 on 2023-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0015_alter_vehicledetails_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_card_no', models.BigIntegerField()),
                ('card_cvv', models.IntegerField()),
                ('card_name', models.CharField(max_length=250)),
                ('card_validity', models.DateTimeField()),
                ('card_type', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
