# Generated by Django 4.1.7 on 2023-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0016_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
