# Generated by Django 4.1.7 on 2023-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0016_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='alert_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterModelTable(
            name='alerts',
            table='alerts',
        ),
    ]
