# Generated by Django 4.1.7 on 2023-03-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0017_alter_alerts_alert_status_alter_alerts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_user_fcm',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
