# Generated by Django 4.1.7 on 2023-03-16 04:20

from django.db import migrations, models
import django.db.models.deletion
import openup_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0018_session_session_user_fcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='vehicle_license',
            field=models.FileField(upload_to=openup_app.models.file_name),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vehicle_license',
            field=models.FileField(blank=True, null=True, upload_to=openup_app.models.file_name),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('feedback_status', models.BooleanField(default=0)),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('feedback_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openup_app.jobs')),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
