# Generated by Django 4.1.7 on 2023-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0019_alter_jobs_vehicle_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_stars',
            field=models.FloatField(null=True),
        ),
    ]
