# Generated by Django 4.1.7 on 2023-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0020_feedback_feedback_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_stars',
            field=models.FloatField(default=1),
        ),
    ]
