# Generated by Django 4.1.7 on 2023-03-16 06:20

from django.db import migrations, models
import openup_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0022_alter_feedback_feedback_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='vehicle_license',
            field=models.FileField(null=True, upload_to=openup_app.models.file_name),
        ),
    ]
