# Generated by Django 4.1.7 on 2023-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0023_alter_jobs_vehicle_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
