# Generated by Django 4.1.7 on 2023-03-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0024_alter_registration_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='location',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='location_not',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='only_using',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='ser_feed_not',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='service_not',
        ),
        migrations.AddField(
            model_name='settings',
            name='setting_name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='setting_value',
            field=models.BooleanField(default=0),
        ),
    ]
