# Generated by Django 4.1.7 on 2023-03-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0025_remove_settings_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='user',
            new_name='setting_user',
        ),
    ]
