# Generated by Django 4.1.7 on 2023-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0026_rename_user_settings_setting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_fcm_token',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
