# Generated by Django 4.1.7 on 2023-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0027_alter_registration_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_user_fcm',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
