# Generated by Django 4.1.7 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0028_alter_session_session_user_fcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='device_type',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
