# Generated by Django 4.1.7 on 2023-03-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0029_alter_registration_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='employee_status',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
