# Generated by Django 4.1.7 on 2023-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0030_registration_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_card_no',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_fcm_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
