# Generated by Django 4.1.7 on 2023-03-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0032_alter_payment_user_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_stripe_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
