# Generated by Django 4.1.7 on 2023-03-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0033_payment_card_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_stripe_id',
            new_name='card_stripe_payment_id',
        ),
    ]
