# Generated by Django 4.1.7 on 2023-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0035_rename_card_stripe_payment_id_payment_card_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_stripe_id',
            new_name='card_customer_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='card_method_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
