# Generated by Django 4.1.7 on 2023-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0036_rename_card_stripe_id_payment_card_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_is_verified',
            field=models.BooleanField(default=1),
        ),
    ]
