# Generated by Django 4.1.7 on 2023-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0037_registration_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_pay_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
