# Generated by Django 4.1.7 on 2023-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0038_jobs_job_pay_status_jobs_job_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_stripe_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
