# Generated by Django 4.1.7 on 2023-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0039_registration_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
