# Generated by Django 4.1.7 on 2023-03-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0040_registration_user_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFailedInfo',
            fields=[
                ('payment_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('job_id', models.CharField(max_length=10)),
                ('payment_fail_type', models.CharField(max_length=50)),
                ('payment_fail_code', models.CharField(max_length=50)),
                ('payment_fail_message', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'paymentfailedinfo',
            },
        ),
    ]
