# Generated by Django 4.1.7 on 2023-03-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0041_paymentfailedinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_type',
            field=models.CharField(max_length=100),
        ),
    ]
