# Generated by Django 4.1.7 on 2023-04-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0042_alter_paymentfailedinfo_payment_fail_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_type',
            field=models.CharField(max_length=500),
        ),
    ]
