# Generated by Django 4.1.7 on 2023-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0044_alter_paymentfailedinfo_payment_fail_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
