# Generated by Django 4.1.7 on 2023-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0045_jobs_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_distance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
