# Generated by Django 4.1.7 on 2023-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0046_jobs_job_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVerification',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=10)),
                ('link_user_email', models.CharField(max_length=50)),
                ('link_token', models.CharField(max_length=500)),
                ('link_status', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'accountverification',
            },
        ),
    ]
