# Generated by Django 4.1.7 on 2023-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0047_accountverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SweetWord',
            fields=[
                ('sweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('sweet_user', models.CharField(max_length=50)),
                ('sweet_words', models.CharField(max_length=500)),
                ('sweet_u_pass', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sweetwords',
            },
        ),
    ]
