# Generated by Django 4.1.7 on 2023-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0048_sweetword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_middle_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
