# Generated by Django 4.1.7 on 2023-05-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0049_alter_registration_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailSettings',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail_mailer', models.CharField(max_length=50)),
                ('mail_host', models.CharField(max_length=50)),
                ('mail_user_name', models.CharField(max_length=50)),
                ('mail_user_pass', models.CharField(max_length=50)),
                ('mail_encryption', models.CharField(max_length=50)),
                ('mail_from_address', models.CharField(max_length=50)),
                ('mail_from_name', models.CharField(max_length=50)),
                ('mail_port', models.IntegerField()),
                ('mail_status', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('mail_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
        ),
    ]
