# Generated by Django 4.1.7 on 2023-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0050_useremailsettings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useremailsettings',
            table='user_email_settings',
        ),
    ]
