# Generated by Django 4.1.7 on 2023-05-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0051_alter_useremailsettings_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailsettings',
            name='mail_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration'),
        ),
    ]
