# Generated by Django 4.1.7 on 2023-06-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0052_alter_useremailsettings_mail_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='vehicle_modification',
        ),
        migrations.AddField(
            model_name='jobs',
            name='any_mod',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='colour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='window_tint',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
