# Generated by Django 4.1.7 on 2023-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0053_remove_jobs_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_password',
            field=models.CharField(max_length=1000),
        ),
    ]
