# Generated by Django 4.1.7 on 2023-06-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0054_alter_registration_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_paypal_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
