# Generated by Django 4.1.7 on 2023-06-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0055_registration_user_paypal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user_paypal_id',
        ),
        migrations.CreateModel(
            name='PaypalInfo',
            fields=[
                ('paypal_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('paypal_valut_id', models.CharField(max_length=50)),
                ('paypal_cust_id', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('paypal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'paypal_cust_info',
            },
        ),
    ]
