# Generated by Django 4.1.7 on 2023-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0056_remove_registration_user_paypal_id_paypalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('webhook_id', models.AutoField(primary_key=True, serialize=False)),
                ('webhook_data', models.CharField(max_length=1000)),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'webhook_data',
            },
        ),
    ]
