# Generated by Django 4.1.7 on 2023-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0057_webhookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessPayments',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_user', models.CharField(max_length=100)),
                ('pay_job', models.CharField(max_length=1000)),
                ('pay_response', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sucess_payments',
            },
        ),
    ]
