# Generated by Django 4.1.7 on 2026-07-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0058_successpayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=100, null=True)),
                ('log_msg', models.CharField(max_length=200, null=True)),
                ('cancel_by', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'job_log',
            },
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vehicle_modification',
        ),
        migrations.AddField(
            model_name='jobs',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentfailedinfo',
            name='payment_fail_response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paypalinfo',
            name='paypal_response',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_payment_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='successpayments',
            name='pay_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='any_mod',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='colour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='window_tint',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='webhook_type',
            field=models.CharField(default='request', max_length=150),
        ),
        migrations.AlterField(
            model_name='paymentfailedinfo',
            name='payment_fail_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookdata',
            name='webhook_data',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_type', models.IntegerField(null=True)),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.jobs')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='attachments')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.TextField(null=True)),
                ('file_system_name', models.TextField(null=True)),
                ('file_s3_path', models.TextField(null=True)),
                ('file_size', models.IntegerField(null=True)),
                ('file_status', models.IntegerField(default=1)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('udated_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=0)),
                ('file_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='openup_app.images')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
