# Generated by Django 4.1.7 on 2026-07-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0059_joblogs_remove_vehicledetails_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_attempted_by',
            field=models.TextField(default='', null=True),
        ),
    ]
