# Generated by Django 4.1.7 on 2026-08-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0060_add_job_attempted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
