# Generated by Django 4.1.7 on 2026-07-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0060_add_job_attempted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalinfo',
            name='paypal_source_type',
            field=models.CharField(choices=[('card', 'card'), ('venmo', 'venmo'), ('paypal', 'paypal')], default='card', max_length=20),
        ),
    ]
