# Generated by Django 4.1.7 on 2026-08-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openup_app', '0061_feedback_comment_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenmoInfo',
            fields=[
                ('venmo_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('venmo_vault_id', models.CharField(max_length=50)),
                ('venmo_cust_id', models.CharField(max_length=100)),
                ('venmo_email', models.CharField(blank=True, max_length=150, null=True)),
                ('venmo_response', models.TextField(default='text')),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
                ('venmo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openup_app.registration')),
            ],
            options={
                'db_table': 'venmo_cust_info',
            },
        ),
    ]
