"""
Django settings for openup project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
# Import os 
import os
 

# CODE FOR ENV
import environ
env = environ.Env()
environ.Env.read_env()
# CODE FOR ENV END


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# TEMPLATE_DIR = os.path.join(BASE_DIR,'TEMPLATES')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY      =   'django-insecure-1g*)i!^u31(^hla+6a47dyhm#_vkz)xlv$c%%%_^vq%fe=y^lv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG           =   False
ADMIN_ENABLED   =   False
# ALLOWED ALL HOST

ALLOWED_HOSTS   =   ['*']


#  CELERY SETTINGS 

os.environ.get('REDIS_URL')
CELERY_BROKER_URL                   =       'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND               =       'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT               =       ['application/json']
CELERY_RESULT_SERIALIZER            =       'json'
CELERY_TASK_SERIALIZER              =       'json'
CELERY_RESULT_BACKEND               =       'django-db'
CELERY_STORE_ERRORS_EVEN_IF_IGNORED =       True

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'openup.settings')

 

# Application definition
INSTALLED_APPS = [
   
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'openup_api',
    'openup_app',
    'rest_framework',
    'django_celery_results' 
    
]


ADMIN_ENABLED = True

BACKGROUND_TASK_RUN_ASYNC = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'openup_app.Middlewares.AsyncMiddleware.AsyncMiddleware',
]



# TEMPLATE CONFIGURAION

TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'openup.wsgi.application'

# EMAIL SETTINGS
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
 


EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL       = env('EMAIL_USE_SSL')
EMAIL_HOST          = env('EMAIL_HOST')
EMAIL_HOST_USER     = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT          = env('EMAIL_PORT')










# DATABASE SETTINGS

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  
        'NAME'      : env('DATABASE_NAME'),
        'USER'      : env('DATABASE_USER'),
        'PASSWORD'  : env('DATABASE_PASS'),
        'HOST'      : env('DATABASE_HOST'),   # Or an IP Address that your DB is hosted on
        'PORT'      : env('DATABASE_PORT'),
    },

        # 'TEST': {
        # # testing database customization here
        # 'ENGINE': 'django.db.backends.mysql',  
        # 'NAME': 'test_openup',
        #  'USER'      : env('DATABASE_USER'),
        # 'PASSWORD'  : env('DATABASE_PASS'),
        # 'HOST'      : env('DATABASE_HOST'),   # Or an IP Address that your DB is hosted on
        # 'PORT'      : env('DATABASE_PORT'),
        # }
    }




# DATABASES['default'] = DATABASES['TEST']


'''STRIPE CONFIGURATION'''
 


#Static File Configuration


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = [
#      STATIC_ROOT,
# ]
X_FRAME_OPTIONS = 'ALLOW-FROM  http://192.168.1.2:8000/api/'
 

# Media File Configuration 
 
MEDIA_URL = '/media/'
MEDIA_DIR = os.path.join(BASE_DIR,'media').replace('\\', '/')
MEDIA_ROOT = MEDIA_DIR 



ROOT_URLCONF = 'openup.urls'


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
 

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import logging
# ERROR LOG FOR WARNIN 
 
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
  
    'handlers': {
        'file':{
            
            'level': 'INFO',
            'class':'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(BASE_DIR,'debug_logs.log'),
            'formatter':'custom_format',
           
        },
              

    },
    'loggers': {
    
            'django.request':{
                'handlers': ['file'],
                'level': 'DEBUG',  
                'propagate' : False
            },
    },
     'formatters':{
        'custom_format':{
            'format': '{levelname} {asctime} {message} ',
            'style' :'{',
        }

    },
}


CSRF_TRUSTED_ORIGINS = ['https://app.opnup.net']
