# Create your views here.
from rest_framework.decorators import api_view


# import Json Response
from django.http.response import JsonResponse, HttpResponseBadRequest

# Import token verifications
from openup_api.views.auth_views import token_verification
from datetime import datetime
from django.utils import timezone

import requests
import json
from django.http import HttpRequest
#  Import Serializer
from openup_app.serializers import RegisterSerializer
from openup_app.models import Registration, PaypalInfo, WebhookData
from django.views.decorators.csrf import csrf_exempt

 
import environ 
env = environ.Env()
environ.Env.read_env()

# tehatol844@iturchia.com
# # wokring Sandbox credentials for openupweb  generated by akshay sir

# client_id       =   'Ad3dW3Sh08cRnMWsj-W0BTN5X3A2Bo1P-Hr9VHpdqR3kJRXHXksMdTm8RceH8AhivC2JzQ31AAq70WdX'
# client_secret   =   'EFnX_7yqdCpe2FuXowuWt8xRTD9RYeoxfvzhRv3Knt64BBybEJlizFr6K4011mstG5tayi7ggSFqnsyw'

# SET CLIENT ID AND SECRET IN .ENV FILE

client_id=env("CLIENT_ID")
client_secret=env("CLIENT_SECRET")

# tehatol844@iturchia.com


# CREATE FIRST PAYMENT IN PAYPAL AND SAVE VALUT ID FOR LATER USE working

@api_view(['POST'])
def create_customer(request):
    token = request.headers.get('Authorization')
    user_token = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    
    check_user = token_verification(user_token)
    
    if check_user is None:
        return JsonResponse({
            "success": 0,
            "message": "Unauthorized User",
        })
    else:
        
        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)
        response        =   requests.post(url, headers=headers, data=data, auth=auth)

        access_token    =   response.json()['access_token']

        # REQUIRED DATA FOR PAYMENT
        card_no          =  request.data.get('card_no')
        expiry           =  request.data.get('expiry')
        card_holder_name =  request.data.get('card_holder_name')
        address_line_1   =  request.data.get('address_line_1')
        address_line_2   =  request.data.get('address_line_2')
        admin_area_2     =  request.data.get('admin_area_2')  
        admin_area_1     =  request.data.get('admin_area_1')
        postal_code      =  request.data.get('postal_code')
        country_code     =  request.data.get('country_code')
        paypal_req_id    =  request.data.get('paypal_req_id') # random text 
        # access_token     =  request.data.get('access_token')

        
        login_customer = check_user['session_user']
        user = Registration.objects.get(user_id=login_customer)

        #  payapl authentication
        headers = {
            'Content-Type': 'application/json',
            'PayPal-Request-Id': paypal_req_id,  # change id on each request
            'Authorization': 'Bearer '+ access_token,
        }

        # Working static data 
        data = {
        "intent": "CAPTURE",
        "payment_source": {
                "card": {
                    "number": "4111111111111111",
                    "expiry": "2024-04",
                    "name": "Akshay pathak",
                    "billing_address": {
                        "address_line_1": "2211 N First Street",
                        "address_line_2": "Building 17",
                        "admin_area_2": "San Jose",
                        "admin_area_1": "CA",
                        "postal_code": "95131",
                        "country_code": "US"
                    },
                    "attributes": {
                        "vault": {
                            "store_in_vault": "ON_SUCCESS"
                        }
                    }
                }
            },
        "purchase_units": [{
        #      #Change id on each request
             "reference_id": "1122", 
            "amount": {
                "currency_code": "USD",
                "value": "110.00"
            }
        }]
            
            
            }

        # data = {
        # "intent": "CAPTURE",
        # "payment_source": {
        #         "card": {
        #             "number": card_no,
        #             "expiry": expiry,
        #             "name"  : card_holder_name,
        #             "billing_address": {
        #                 "address_line_1": address_line_1,
        #                 "address_line_2": address_line_2,
        #                 "admin_area_2"  : admin_area_2,
        #                 "admin_area_1"  : admin_area_1,
        #                 "postal_code"   : postal_code,
        #                 "country_code"  : country_code
        #             },
        #             "attributes": {
        #                 "vault": {
        #                     "store_in_vault": "ON_SUCCESS"
        #                 }
        #             }
        #         }
        #     },
        # "purchase_units": [
        #     {
        #     "reference_id": "112",    #Change id on each request
        #     "amount": {
        #         "currency_code": "USD",
        #         "value": "110.00"
        #     }
        #     }
        # ]
        # }

        # data = { "intent": "CAPTURE", "purchase_units": [ { "reference_id": "d9f80740-38f0-11e8-b467-0ed5f89f718b", "amount": { "currency_code": "USD", "value": "100.00" } } ], "payment_source": { "paypal": { "experience_context": { "payment_method_preference": "IMMEDIATE_PAYMENT_REQUIRED", "payment_method_selected": "PAYPAL", "brand_name": "EXAMPLE INC", "locale": "en-US", "landing_page": "LOGIN", "shipping_preference": "SET_PROVIDED_ADDRESS", "user_action": "PAY_NOW", "return_url": "https://example.com/returnUrl", "cancel_url": "https://example.com/cancelUrl" } } } }

        #  payapl order api call to save valut id
        response = requests.post('https://api-m.sandbox.paypal.com/v2/checkout/orders/', headers=headers, json=data)

        resp_data = json.loads(response.text)

        try:
            if resp_data["status"] == "COMPLETED":
                
                valut_id = resp_data['payment_source']["card"]["attributes"]["vault"]["id"]

                cust_id  = resp_data['payment_source']["card"]["attributes"]["vault"]["customer"]["id"]

                paypal_data = PaypalInfo(
                            paypal_user     =   user,
                            paypal_valut_id =   valut_id,
                            paypal_response =   resp_data,
                            paypal_cust_id  =   cust_id,
                            is_delete       =   0,
                            created_at      =    timezone.now()  
                )
                paypal_data.save()

                return JsonResponse({
                            "success"       :   1,
                            "message"       :   "payment success",
                            "data"          :   resp_data

                    })  
        except:
            pass           
        else:
             
            return JsonResponse({
                    "success"       :   0,
                    "message"       :   "Something went wrong",
                     
            })
    return JsonResponse({
                    "success"       :   0,
                    "message"       :   "Something went wrong",
                     
            })
         



# Code for future payments   =>working
# PAYMENT BY USING PAYPAL CUSTOMER ID

@api_view(['POST'])

def paypal_payment(request):

    token       = request.headers.get('Authorization')
    user_token  = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    check_user  = token_verification(user_token)
    
    if check_user is None:
        return JsonResponse({
            "success": 0,
            "message": "Unauthorized User",
        })
    
    else:
        paypal_req_id   =   request.data.get('paypal_req_id')  # random text 
        login_user      =   check_user['session_user']
        paypal_data     =   PaypalInfo.objects.filter(paypal_user=login_user).values().first()
        
        # get access token
        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US', 'PayPal-Request-Id': paypal_req_id,}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)
        response        =   requests.post(url, headers=headers, data=data, auth=auth)
        access_token    =   response.json()['access_token']
 
        # # Create payment payload
        # payload = {
        #     "intent": "CAPTURE",
        #     "payer": {
        #         "payment_method": "paypal",
        #         "payer_info": {
        #             "customer_id": paypal_data['paypal_cust_id']
        #         }
        #     },
        #      "purchase_units": [
        #     {
        #     "reference_id": "111",    #Change id on each request
        #     "amount": {
        #         "currency_code": "USD",
        #         "value": "110.00"
        #     }
        #     }
        # ],
        #     "payee": {
        #         "merchant_id": paypal_data['paypal_valut_id'] 
        #     }
        # }

        # FUTURE PAYMENTS WILL BE CREATED BY USING VALUT ID 

        payload={
            "intent": "CAPTURE",
            "purchase_units": [
                {
                    "amount": {
                        "currency_code": "USD",
                        "value": "100.00"
                    }
                }
            ],
            "payment_source": {
                "card": {
                    "vault_id":paypal_data['paypal_valut_id'] 
                            }          
                        }
                    }

        # Send payment request
        url = 'https://api-m.sandbox.paypal.com/v2/checkout/orders'
        headers = {'Content-Type': 'application/json','PayPal-Request-Id': paypal_req_id, 'Authorization': 'Bearer ' +access_token}
        response = requests.post(url, headers=headers, json=payload)
        response_data = response.json()
         
        return JsonResponse({
                        "success"       :   1,
                        "message"       :   "payment success",
                        "data"          :   response_data
                })   




# THIS API WILL CREATE WEBHOOK 
# CURRENT URL MUST BE NEW URL AT TIME OF WEBHOOK CREATION
@api_view(['POST'])

def create_webhook(request: HttpRequest):
    # random text 
    paypal_req_id   =   request.data.get('paypal_req_id') 
    url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
    headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US', 'PayPal-Request-Id': paypal_req_id,}
    data            =   {'grant_type': 'client_credentials'}
    auth            =   (client_id, client_secret)
    response        =   requests.post(url, headers=headers, data=data, auth=auth)
    access_token    =   response.json()['access_token']
   
    request_data = response.json()
    # SAVE REQUEST DATA
    webhook_data    =   WebhookData(
        webhook_type   =  "request", 
        webhook_data   =   request_data,
        is_delete       =   0,
        created_at      =   timezone.now()
    )

    webhook_data.save()
    headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer '+access_token,
    }

    # current_url = request.build_absolute_uri()
     
    # current_url = 'https://www.openupwebsoln.com'
    current_url = 'http://138.197.0.56:8000'
 
    data = { "url": current_url, "event_types": 
            [ 
                { 
                    "name": "PAYMENT.AUTHORIZATION.CREATED" 
                }, 
                { 
                    "name": "PAYMENT.AUTHORIZATION.VOIDED" 
                } 
            ] 
    }
    response = requests.post('https://api-m.sandbox.paypal.com/v1/notifications/webhooks', headers=headers, json=data)

    resp_data = json.loads(response.text)
    # data      = json.loads(resp_data)

    # SAVE ERROR OR RESPONSE OF WEBHOOK CREATION
    try:
        if resp_data['name']:
            webhook_data    =   WebhookData(
                webhook_type   =  "error",
                webhook_data   =   resp_data,
                is_delete       =   0,
                created_at      =   timezone.now()

            )
            webhook_data.save()

            return JsonResponse({
                        "success"       :   0,
                        "message"       :   "something went wrong",
                        "data"          :   resp_data
                    })
    except:
        pass    
    webhook_data    =   WebhookData(
        webhook_type   =  "response",
        webhook_data   =   resp_data,
        is_delete       =   0,
        created_at      =   timezone.now()
    )   
    webhook_data.save()

    return JsonResponse({
                        "success"       :   1,
                        "message"       :   "webhook created",
                        "data"          :   resp_data
                        })  
    
    




# PAYPAL WILL CALL THIS API AND SAVE TOKEN IN DATABASE

@api_view(['POST'])

def paypal_payment_token_receiver(request):

        token_info = request.data.get('token_receiver_info')    
        data       = json.loads(token_info)


        webhook_data    =   WebhookData(
            webhook_data   =   data,
            is_delete       =   0,
            created_at      =   timezone.now()
        )

        webhook_data.save()

        return JsonResponse({
                            "success"       :   1,
                            "message"       :   "paypal information received ",
                    })  








 

# RECEIVE WEBHOOK DATA AND SAVE IT TO THE DATABASE


@csrf_exempt

def receive_webhook_data(request):

    try:
        payload = json.loads(request.body)
        
        # Process the webhook data
       
        # Save data in webhook
        webhook_data    =   WebhookData(
                webhook_data   =   payload,
                is_delete       =   0,
                created_at      =   timezone.now()
            )

        webhook_data.save()
        
    # except ValueError:
    #     return HttpResponseBadRequest("Invalid JSON payload")
    except:
        pass

    return JsonResponse({
                            "success"       :   1,
                            "message"       :   "paypal information received ",
                    })  



 









@api_view(['POST'])
    # Save the customer ID for later use
def save_customer_id(customer_id):
        # You can implement your own logic to save the customer ID, such as storing it in a database or file
        # For demonstration purposes, we'll simply print it here


        # Usage
        customer_id = create_customer()

        pass 
        if customer_id:
            save_customer_id(customer_id)



@api_view(['POST'])

def create_paypal_token(request):
    token = request.headers.get('Authorization')
    user_token = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    
    check_user = token_verification(user_token)
    
    if check_user is None:
        return JsonResponse({
            "success": 0,
            "message": "Unauthorized User",
        })
    else:

        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)
        response        =   requests.post(url, headers=headers, data=data, auth=auth)

        access_token    =   response.json()['access_token']
        paypal_req_id    =  request.data.get('paypal_req_id') # random text 

        login_customer = check_user['session_user']
        user = Registration.objects.get(user_id=login_customer)

            #  payapl authentication
        headers = {
            'Content-Type': 'application/json',
            'PayPal-Request-Id': paypal_req_id,  # change id on each request
            'Authorization': 'Bearer '+ access_token,
        }


        data={
            "payment_source": {
                "card": {
                    "number": "4111111111111111",
                    "expiry": "2027-02",
                    "name": "Firstname Lastname",
                    "billing_address": {
                        "address_line_1": "2211 N First Street",
                        "address_line_2": "17.3.160",
                        "admin_area_1": "CA",
                        "admin_area_2": "San Jose",
                        "postal_code": "95131",
                        "country_code": "US"
                    },
                    
                }
            }
        }
        response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/setup-tokens', headers=headers, json=data)

        resp_data = json.loads(response.text)

        try:
            if resp_data["status"] == "COMPLETED":
                
                valut_id = resp_data['payment_source']["card"]["attributes"]["vault"]["id"]

                cust_id  = resp_data['payment_source']["card"]["attributes"]["vault"]["customer"]["id"]

                paypal_data = PaypalInfo(
                            paypal_user     =   user,
                            paypal_valut_id =   valut_id,
                            paypal_response =   resp_data,
                            paypal_cust_id  =   cust_id,
                            is_delete       =   0,
                            created_at      =    timezone.now()  
                )
                paypal_data.save()

                return JsonResponse({
                            "success"       :   1,
                            "message"       :   "payment success",
                            "data"          :   resp_data

                    })  
        except:
            pass           
        else:
                
            return JsonResponse({
                    "success"       :   0,
                    "message"       :   "Something went wrong",
                        
            })
        return JsonResponse({
                        "success"       :   0,
                        "message"       :   "Something went wrong",
                            
                })


