# Create your views here.
from rest_framework.decorators import api_view


# import Json Response
from django.http.response import JsonResponse, HttpResponseBadRequest

# Import token verifications
from openup_api.views.auth_views import token_verification
from datetime import datetime
from django.utils import timezone
import stripe
import requests
import json
from django.http import HttpRequest
#  Import Serializer
from openup_app.serializers import PaymentFailedInfoSerializer,RegisterSerializer
from openup_app.models import Registration, PaypalInfo, WebhookData,Jobs, Payment,PaymentFailedInfo
from django.views.decorators.csrf import csrf_exempt

# import Payments class 
from openup.background_paypal import PaypalPayment

from openup.paypal_first_payment import First_PayPal_Payment

from celery import shared_task
from django.db.models import Q

# from openup.background_paypal import backgoun
from openup.create_cust import stripeCustomer



# import stripeCustomer to create cust in stripe run in background process


import environ 
env = environ.Env()
environ.Env.read_env()


# Import Serializer
from openup_app.serializers import JobsSerializer   

# tehatol844@iturchia.com
# # wokring Sandbox credentials for openupweb  generated by akshay sir

# client_id       =   'Ad3dW3Sh08cRnMWsj-W0BTN5X3A2Bo1P-Hr9VHpdqR3kJRXHXksMdTm8RceH8AhivC2JzQ31AAq70WdX'
# client_secret   =   'EFnX_7yqdCpe2FuXowuWt8xRTD9RYeoxfvzhRv3Knt64BBybEJlizFr6K4011mstG5tayi7ggSFqnsyw'

# SET CLIENT ID AND SECRET IN .ENV FILE

client_id=env("CLIENT_ID")
client_secret=env("CLIENT_SECRET")

# tehatol844@iturchia.com


# CREATE FIRST PAYMENT IN PAYPAL AND SAVE VALUT ID FOR LATER USE working

@api_view(['POST'])
def create_customer(request):

    token           = request.headers.get('Authorization')
    user_token      = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    check_user      = token_verification(user_token)
    paypal_req_id   =  request.data.get('paypal_req_id')
    if check_user is None:
        return JsonResponse({
            "success": 2,
            "message": "Unauthorized User",
        })
    else:
        

        login_customer  = check_user['session_user']
        user            = Registration.objects.get(user_id=login_customer)

        # To get access token 
        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)

        response        =   requests.post(url, headers=headers, data=data, auth=auth)

        access_token    =   response.json()['access_token']


        #  payapl authentication
        headers = {
            'Content-Type': 'application/json',
            'PayPal-Request-Id': paypal_req_id,  # change id on each request
            'Authorization': 'Bearer '+ access_token,
        }

        #  Paypal payload
        data={
                "payment_source": {
                    "card": {
                        "number": "4111111111111111",
                        "expiry": "2027-02",
                        "name": "Firstname Lastname",
                        "billing_address": {
                            "address_line_1": "2211 N First Street",
                            "address_line_2": "17.3.160",
                            "admin_area_1": "CA",
                            "admin_area_2": "San Jose",
                            "postal_code": "95131",
                            "country_code": "US"
                        },
                        "experience_context": {
                            "brand_name": "YourBrandName",
                            "locale": "en-US",
                            "return_url": "https://example.com/returnUrl",
                            "cancel_url": "https://example.com/cancelUrl"
                        }
                    }
                }
            }
        #  set up payment token
        response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/setup-tokens', headers=headers, json=data)

        resp_data = json.loads(response.text)
         
        payment_method_id = resp_data["id"]

        # 
        payment_method_payload = {
                "payment_source": {
                    "token": {
                        "id": payment_method_id,
                        "type": "SETUP_TOKEN"
                    }
                }
            }

        response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/payment-tokens', headers=headers, json=payment_method_payload)
        resp_data = json.loads(response.text)
        

        valut_id =  resp_data["id"]
        cust_id  =  resp_data["customer"]["id"]


        paypal_data = PaypalInfo(
                    paypal_user     =   user,
                    paypal_valut_id =   valut_id,
                    paypal_response =   resp_data,
                    paypal_cust_id  =   cust_id,
                    is_delete       =   0,
                    created_at      =    timezone.now()  
        )
        paypal_data.save()



        return JsonResponse({
            "success"       :   0,
            "message"       :   "Something went wrong",
            "data"          :   resp_data       
        })


              


    # Working code
    # token = request.headers.get('Authorization')
    # user_token = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    
    # check_user = token_verification(user_token)
    
    # if check_user is None:
    #     return JsonResponse({
    #         "success": 2,
    #         "message": "Unauthorized User",
    #     })
    # else:
        
    #     url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
    #     headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
    #     data            =   {'grant_type': 'client_credentials'}
    #     auth            =   (client_id, client_secret)
    #     response        =   requests.post(url, headers=headers, data=data, auth=auth)

    #     access_token    =   response.json()['access_token']

    #     # REQUIRED DATA FOR PAYMENT
    #     card_no          =  request.data.get('card_no')
    #     expiry           =  request.data.get('expiry')
    #     card_holder_name =  request.data.get('card_holder_name')
    #     address_line_1   =  request.data.get('address_line_1')
    #     address_line_2   =  request.data.get('address_line_2')
    #     admin_area_2     =  request.data.get('admin_area_2')  
    #     admin_area_1     =  request.data.get('admin_area_1')
    #     postal_code      =  request.data.get('postal_code')
    #     country_code     =  request.data.get('country_code')
    #     paypal_req_id    =  request.data.get('paypal_req_id') # random text 
    #     # access_token     =  request.data.get('access_token')
    #     job_id           =   request.data.get('job_id')
        
    #     login_customer = check_user['session_user']
    #     # user = Registration.objects.get(user_id=login_customer)

    #     #  payapl authentication
    #     headers = {
    #         'Content-Type': 'application/json',
    #         'PayPal-Request-Id': paypal_req_id,  # change id on each request
    #         'Authorization': 'Bearer '+ access_token,
    #     }

    #     # Working static data 
    #     data = {
    #     "intent": "CAPTURE",
    #     "payment_source": {
    #             "card": {
    #                 "number": "	374245455400126",
    #                 "expiry": "2024-04",
    #                 "name": "Swap pathak",
    #                 "billing_address": {
    #                     "address_line_1": "2211 N First Street",
    #                     "address_line_2": "Building 17",
    #                     "admin_area_2": "San Jose",
    #                     "admin_area_1": "CA",
    #                     "postal_code": "95131",
    #                     "country_code": "US"
    #                 },
    #                 "attributes": {
    #                     "vault": {
    #                         "store_in_vault": "ON_SUCCESS"
    #                     }
    #                 }
    #             }
    #         },
    #     "purchase_units": [{
    #     #      #Change id on each request
    #          "reference_id": "1132", 
    #         "amount": {
    #             "currency_code": "USD",
    #             "value": "110.00"
    #         }
    #     }]
    #         }

    #     # data = {
    #     # "intent": "CAPTURE",
    #     # "payment_source": {
    #     #         "card": {
    #     #             "number": card_no,
    #     #             "expiry": expiry,
    #     #             "name"  : card_holder_name,
    #     #             "billing_address": {
    #     #                 "address_line_1": address_line_1,
    #     #                 "address_line_2": address_line_2,
    #     #                 "admin_area_2"  : admin_area_2,
    #     #                 "admin_area_1"  : admin_area_1,
    #     #                 "postal_code"   : postal_code,
    #     #                 "country_code"  : country_code
    #     #             },
    #     #             "attributes": {
    #     #                 "vault": {
    #     #                     "store_in_vault": "ON_SUCCESS"
    #     #                 }
    #     #             }
    #     #         }
    #     #     },
    #     # "purchase_units": [
    #     #     {
    #     #     "reference_id": "112",    #Change id on each request
    #     #     "amount": {
    #     #         "currency_code": "USD",
    #     #         "value": "110.00"
    #     #     }
    #     #     }
    #     # ]
    #     # }

    #     # data = { "intent": "CAPTURE", "purchase_units": [ { "reference_id": "d9f80740-38f0-11e8-b467-0ed5f89f718b", "amount": { "currency_code": "USD", "value": "100.00" } } ], "payment_source": { "paypal": { "experience_context": { "payment_method_preference": "IMMEDIATE_PAYMENT_REQUIRED", "payment_method_selected": "PAYPAL", "brand_name": "EXAMPLE INC", "locale": "en-US", "landing_page": "LOGIN", "shipping_preference": "SET_PROVIDED_ADDRESS", "user_action": "PAY_NOW", "return_url": "https://example.com/returnUrl", "cancel_url": "https://example.com/cancelUrl" } } } }

    #     #  payapl order api call to save valut id

    #     # response = requests.post('https://api-m.sandbox.paypal.com/v2/checkout/orders/', headers=headers, json=data)

    #     # resp_data = json.loads(response.text)

    #     # try:
    #     #     if resp_data["status"] == "COMPLETED":
                
    #     #         valut_id = resp_data['payment_source']["card"]["attributes"]["vault"]["id"]

    #     #         cust_id  = resp_data['payment_source']["card"]["attributes"]["vault"]["customer"]["id"]

    #     #         paypal_data = PaypalInfo(
    #     #                     paypal_user     =   user,
    #     #                     paypal_valut_id =   valut_id,
    #     #                     paypal_response =   resp_data,
    #     #                     paypal_cust_id  =   cust_id,
    #     #                     is_delete       =   0,
    #     #                     created_at      =    timezone.now()  
    #     #         )
    #     #         paypal_data.save()


    #     #         job_record = Jobs.objects.exclude(is_delete=1).get(job_id=int(data['job_id']))   
    #     #         update_payment_status = {
    #     #                 "job_payment_id"    :      data['job_id'],
    #     #                 "job_pay_status"    :      1 
    #     #                 } 
    #     #         job_ser  = JobsSerializer(instance=job_record,data=update_payment_status,partial=True)
    #     #         if job_ser.is_valid():
    #     #             job_ser.save()

    #     #         return JsonResponse({
    #     #                     "success"       :   1,
    #     #                     "message"       :   "payment success",
    #     #                     "data"          :   resp_data

    #     #             })  
    #     # except:
    #     #     # return JsonResponse({
    #     #     #         "success"       :   0,
    #     #     #         "message"       :   "Something went wrong",       
    #     #     # })

    #     #     jobs =  Jobs.objects.get(job_id=job_id)
    #     #     payment_details = {
    #     #         "user_id"               :   user.user_id,
    #     #         "job_id"                :   jobs,
    #     #         "payment_fail_type"     :   resp_data['name'] ,
    #     #         "payment_fail_code"     :   resp_data['body'],
    #     #         "payment_fail_message"  :   resp_data['message'],
    #     #         "created_at"            :   timezone.now(),
    #     #     }

    #     #     payment_ser     =   PaymentFailedInfoSerializer(data=payment_details)
    #     #     if payment_ser.is_valid():
    #     #         payment_ser.save()
             
    #     #         return JsonResponse({
    #     #                 "success"       :   0,
    #     #                 "message"       :   "Something went wrong",
                        
    #     #         })
    #     #     else:
    #     #         return JsonResponse({
    #     #                     "success"       :   0,
    #     #                     "message"       :   "Something went wrong",
                            
    #     #             })


    #     data_dict = {

    #         "headers"       :headers,
    #         "payloads"      :data,
    #         "url"           : url,
    #         "job_id"        :job_id,
    #         "user"          : login_customer
    #             }


    #     first_payment.delay(data_dict)
    #     # first_payment(data_dict)
    #     return JsonResponse({
    #                     "success"       :   1,
    #                     "message"       :   "payment success",

    #             })  








@shared_task()
def first_payment(data):

    First_PayPal_Payment.background_payments(data)
    return True









# Code for future payments   =>working
# PAYMENT BY USING PAYPAL CUSTOMER ID

@api_view(['POST'])

def paypal_payment(request):

     

        # Working code of recurring payment

    token       = request.headers.get('Authorization')
    user_token  = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    check_user  = token_verification(user_token)
    
    if check_user is None:
        return JsonResponse({
            "success": 2,
            "message": "Unauthorized User",
        })
    
    else:
        job_id           =   request.data.get('job_id')
        paypal_req_id   =   request.data.get('paypal_req_id')  # random text 
        login_user      =   check_user['session_user']
        paypal_data     =   PaypalInfo.objects.filter(paypal_user=login_user).values().first()
        
        # get access token
        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US', 'PayPal-Request-Id': paypal_req_id,}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)
        response        =   requests.post(url, headers=headers, data=data, auth=auth)
        access_token    =   response.json()['access_token']
 
        # # Create payment payload
        # payload = {
        #     "intent": "CAPTURE",
        #     "payer": {
        #         "payment_method": "paypal",
        #         "payer_info": {
        #             "customer_id": paypal_data['paypal_cust_id']
        #         }
        #     },
        #      "purchase_units": [
        #     {
        #     "reference_id": "111",    #Change id on each request
        #     "amount": {
        #         "currency_code": "USD",
        #         "value": "110.00"
        #     }
        #     }
        # ],
        #     "payee": {
        #         "merchant_id": paypal_data['paypal_valut_id'] 
        #     }
        # }

        # FUTURE PAYMENTS WILL BE CREATED BY USING VALUT ID 

        payload={
            "intent": "CAPTURE",
            "purchase_units": [
                {
                    "amount": {
                        "currency_code": "USD",
                        "value": "100.00"
                    }
                }
            ],
            "payment_source": {
                "card": {
                    "vault_id":paypal_data['paypal_valut_id'] 
                            }          
                        }
                    }

        # # Send payment request
        # url = 'https://api-m.sandbox.paypal.com/v2/checkout/orders'
        # headers = {'Content-Type': 'application/json','PayPal-Request-Id': paypal_req_id, 'Authorization': 'Bearer ' +access_token}
        # response = requests.post(url, headers=headers, json=payload)
        # response_data = response.json()
         

        payload_data = {
            "paypal_req_id" :   paypal_req_id,
            "payload"       :   payload,
            "access_token"  :   access_token,
            "url"           :   url,
            "job_id"        :   job_id
            }
        # SEND PAYLOAD TO BACKGROUND TO INITIATE PAYMENT

        background_payment.delay(login_user,payload_data)
        data = {
            "job_id" : id,
        }
        # Update job after successfull payment.
        job_record = Jobs.objects.exclude(is_delete=1).get(job_id=int(data['job_id']))   

        
        update_payment_status = {
                "job_payment_id"    :      data['job_id'],
                "job_pay_status"    :      1 
                } 
        
        job_ser  = JobsSerializer(instance=job_record,data=update_payment_status,partial=True)
        if job_ser.is_valid():
            job_ser.save()
        return JsonResponse({
                        "success"       :   1,
                        "message"       :   "payment success",

                })   



# Initiate payment in background

# This code is for reccuring payments


@shared_task()
def background_payment(login_user,data):

    try:
        payment_id  =   Payment.objects.filter(user=int(login_user)).values("login_user").first()["login_user"]  
    except:
        pass

    try:
        payment     =   Payment.objects.get(payment_id=payment_id)
    
    except:
        pass
   
    try:
        user = Registration.objects.exclude(user_is_delete=1).get(user_id=int(login_user))

    except:
        pass

    PaypalPayment.background_payments(data)
    return True
    





# API WILL GET TYPE OF PAYMENT AND THEN SAVE IT TO THE USER TABLE IF IT IS STRIPE

# WORKING CODE OF LIVE


@api_view(['POST'])
def add_payment_type(request):
         
    token = request.headers['Authorization']
    user_token = token.replace("Bearer",'')  
    check_user      =       token_verification(user_token)

    if check_user is None:
        return JsonResponse({
                "success"     :   2,
                "message"     :   "Unauthorized User",
                })
     
    else:

        login_customer = check_user['session_user']

        payment_type = request.data.get('payment_type')
        card_number  = request.data.get('card_number')

        if payment_type != "stripe" and payment_type != "paypal" and payment_type != "apple_pay" and payment_type != "venmo":
            return JsonResponse({
                "success"      :   0,
                "message"      :   "please provide valid payment type",
            })

        '''
        ONLY PAYPAL VAULTS THE CARD HERE, STRIPE CREATES A CUSTOMER, APPLE PAY
        HAS NO CREDENTIAL TO STORE AT ALL, AND VENMO IS VAULTED SEPARATELY VIA
        create-venmo-order / capture-venmo-order (payer approves in Venmo, no
        card number is collected up front)
        '''
        card = None
        if payment_type == "paypal":
            if card_number == None or card_number == "":
                return JsonResponse({
                    "success"      :   0,
                    "message"      :   "please provide card number",
                })
            card = card_number.replace(" ", "")


        user         =   Registration.objects.exclude(user_is_delete=1).get(user_id = login_customer)


        # SAVE PAYMENT TYPE IN USER
        update_data = {
            "user_payment_type" : payment_type
        }
        # user instance to register serializer for update data   
        user_serializer = RegisterSerializer(data=update_data,instance=user,partial=True)
        if user_serializer.is_valid():
            user_serializer.save()
        else:
             return JsonResponse({
            "success"      :   0,
                "message"      :   "something went wrong",

            }) 


        if payment_type == "stripe":
            # CREATE STRIPE CUSTOMER IN BACKGROUND  
            # create_customer.delay(user.user_id)

            # stripe code in foreground

            response_data   =  stripe.Customer.create(description="client added to stripe",
                                       email = user.user_email,
                                       name  = user.user_first_name+' '+user.user_last_name)
            cust_id         = response_data['id']
            # code to create ephemeral key to stripe
            update_data = {
                        "user_stripe_id" : cust_id, 
                       }    
            user_serializer = RegisterSerializer(instance=user,data=update_data,partial=True)
            if user_serializer.is_valid():
                user_serializer.save()
                return JsonResponse({
                    "success"      :   1,
                    "message"      :   "Payment method added successfully",
                    "data"         :    payment_type
                }) 

        if payment_type == "paypal":
            paypal_req_id   =    request.data.get('paypal_req_id')
             
            expiry          =    request.data.get('expiry')

            date = datetime.strptime(expiry,'%m/%y').strftime('%Y-%m')
            
            address         =    request.data.get('address')
            # card_data       =    json.loads(request.body)

             # To get access token 
            url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
            headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
            data            =   {'grant_type': 'client_credentials'}
            auth            =   (client_id, client_secret)

            response        =   requests.post(url, headers=headers, data=data, auth=auth)

            access_token    =   response.json()['access_token']


            #  payapl authentication
            headers = {
                'Content-Type': 'application/json',
                'PayPal-Request-Id': paypal_req_id,  # change id on each request
                'Authorization': 'Bearer '+ access_token,
            }

                #  Paypal payload
            data={
                    "payment_source": {
                        "card": {
                            "number": card,
                            "expiry": date,
                            "name": user.user_first_name,
                            "billing_address": {
                                "address_line_1": address,
                                # "address_line_2": "17.3.160",
                                # "admin_area_1": "CA",
                                # "admin_area_2": "San Jose",
                                # "postal_code": "95131",
                                "country_code": "US"
                            },
                            # "experience_context": {
                            #     "brand_name": "YourBrandName",
                            #     "locale": "en-US",
                            #     "return_url": "https://example.com/returnUrl",
                            #     "cancel_url": "https://example.com/cancelUrl"
                            # }
                        }
                    }
                }
            
             #  set up payment token
            response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/setup-tokens', headers=headers, json=data)

            resp_data = json.loads(response.text)

            try:
                error = resp_data["name"]
            except:
                error = False
            if error == "UNPROCESSABLE_ENTITY" or error == "INVALID_REQUEST":
                paypal_data = PaymentFailedInfo(
                    user_id=user.user_id,job_id="", payment_fail_response=resp_data, created_at=timezone.now()
            )
                paypal_data.save()
                return JsonResponse({
                    "success" : "0",
                    "message"  :    "Invalid request"
                })

            try:
                status = resp_data["status"]
            
            except:
                status = False
            
            if status == "PAYER_ACTION_REQUIRED":
                paypal_data = PaymentFailedInfo(
                    user_id=user.user_id,job_id="", payment_fail_response=resp_data, created_at=timezone.now()
                )
                paypal_data.save()
                return JsonResponse({
                    "success" : "0",
                    "message"  :    "Invalid request"
                })


            payment_method_id = resp_data["id"]

            # 
            payment_method_payload = {
                    "payment_source": {
                        "token": {
                            "id": payment_method_id,
                            "type": "SETUP_TOKEN"
                        }
                    }
                }

            response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/payment-tokens', headers=headers, json=payment_method_payload)
            resp_data = json.loads(response.text)

            try:
                error = resp_data["name"]
            except:
                error = False
           
            # 
            if error == "UNPROCESSABLE_ENTITY" or error == "INVALID_REQUEST":
                paypal_data = PaymentFailedInfo(
                    user_id=user.user_id,job_id="", payment_fail_response=resp_data, created_at=timezone.now()
                )
                paypal_data.save()
                return JsonResponse({
                "success"      :   0,
                "message"      :   "card type not supported",

                }) 

            try:
                status = resp_data["status"]
            
            except:
                status = False
            
            if status == "PAYER_ACTION_REQUIRED":
                paypal_data = PaymentFailedInfo(
                    user_id=user.user_id,job_id="", payment_fail_response=resp_data, created_at=timezone.now()
                )
                paypal_data.save()
                return JsonResponse({
                "success"      :   0,
                "message"      :   "card type not supported",

            }) 



            valut_id =  resp_data["id"]
            cust_id  =  resp_data["customer"]["id"]

            paypal_data = PaypalInfo(
                        paypal_user     =   user,
                        paypal_valut_id =   valut_id,
                        paypal_response =   resp_data,
                        paypal_cust_id  =   cust_id,
                        is_delete       =   0,
                        created_at      =    timezone.now()  
            )
            paypal_data.save()

        '''
        APPLE PAY STORES NOTHING BEYOND user_payment_type - THE TOKEN IS SINGLE USE
        AND EVERY JOB IS PAID UP FRONT THROUGH /apple-pay
        '''

        return JsonResponse({
                "success"      :   1,
                "message"      :   "Payment method added successfully",
                "data"         :    payment_type
            })















# '''create stripe customer in background'''

@shared_task()
def create_customer(user_id):
        stripeCustomer.create_stripe_customer(user_id)


 















# API FOR USER TO DETECT STRIPE OR PAYPAL 

# @api_view(['POST'])
# def payment_type(request):
#     token       = request.headers.get('Authorization')
#     user_token  = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
#     check_user  = token_verification(user_token)
    
#     if check_user is None:
#         return JsonResponse({
#             "success": 2,
#             "message": "Unauthorized User",
#         })
    
#     else:
#         login_customer = check_user['session_user']
        
#         payment_option =  request.data.get('payment_type')


#         user = Registration.objects.exclude(user_is_delete=1).get(user_id=login_customer)

#         # try:
#         #     stripe = user.user_payment_id 
#         # except:
#         #     stripe = None

#         # if stripe == None:
#         #     payment_type = "paypal"
#         # else:
#         #     payment_type = "stripe"

#         update_data = {
#                 "user_payment_type" : payment_option
#             }
#             # user instance to register serializer for update data   
#         user_serializer = RegisterSerializer(data=update_data,instance=user,partial=True)
#         if user_serializer.is_valid():
#             user_serializer.save()

          
#         # if user.user_payment_id 

#         # pass
#         return JsonResponse({
#             "success":  1,
#             "message":  "User payment method",
#             "data"   :  payment_option

#         })









# THIS API WILL CREATE WEBHOOK 
# CURRENT URL MUST BE NEW URL AT TIME OF WEBHOOK CREATION
@api_view(['POST'])

def create_webhook(request: HttpRequest):
    # random text 
    paypal_req_id   =   request.data.get('paypal_req_id') 
    url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
    headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US', 'PayPal-Request-Id': paypal_req_id,}
    data            =   {'grant_type': 'client_credentials'}
    auth            =   (client_id, client_secret)
    response        =   requests.post(url, headers=headers, data=data, auth=auth)
    access_token    =   response.json()['access_token']
   
    request_data = response.json()
    # SAVE REQUEST DATA
    webhook_data    =   WebhookData(
        webhook_type   =  "request", 
        webhook_data   =   request_data,
        is_delete       =   0,
        created_at      =   timezone.now()
    )

    webhook_data.save()
    headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer '+access_token,
    }

    # current_url = request.build_absolute_uri()
     
    # current_url = 'https://www.openupwebsoln.com'
    current_url = 'http://138.197.0.56:8000'
 
    data = { "url": current_url, "event_types": 
            [ 
                { 
                    "name": "PAYMENT.AUTHORIZATION.CREATED" 
                }, 
                { 
                    "name": "PAYMENT.AUTHORIZATION.VOIDED" 
                } 
            ] 
    }
    response = requests.post('https://api-m.sandbox.paypal.com/v1/notifications/webhooks', headers=headers, json=data)

    resp_data = json.loads(response.text)
    # data      = json.loads(resp_data)

    # SAVE ERROR OR RESPONSE OF WEBHOOK CREATION
    try:
        if resp_data['name']:
            webhook_data    =   WebhookData(
                webhook_type   =  "error",
                webhook_data   =   resp_data,
                is_delete       =   0,
                created_at      =   timezone.now()

            )
            webhook_data.save()

            return JsonResponse({
                        "success"       :   0,
                        "message"       :   "something went wrong",
                        "data"          :   resp_data
                    })
    except:
        pass    
    webhook_data    =   WebhookData(
        webhook_type   =  "response",
        webhook_data   =   resp_data,
        is_delete       =   0,
        created_at      =   timezone.now()
    )   
    webhook_data.save()

    return JsonResponse({
                        "success"       :   1,
                        "message"       :   "webhook created",
                        "data"          :   resp_data
                        })  
    
    




# PAYPAL WILL CALL THIS API AND SAVE TOKEN IN DATABASE

@api_view(['POST'])

def paypal_payment_token_receiver(request):

        token_info = request.data.get('token_receiver_info')    
        data       = json.loads(token_info)


        webhook_data    =   WebhookData(
            webhook_data   =   data,
            is_delete       =   0,
            created_at      =   timezone.now()
        )

        webhook_data.save()

        return JsonResponse({
                            "success"       :   1,
                            "message"       :   "paypal information received ",
                    })  








 

# RECEIVE WEBHOOK DATA AND SAVE IT TO THE DATABASE


@csrf_exempt

def receive_webhook_data(request):

    try:
        payload = json.loads(request.body)
        
        # Process the webhook data
       
        # Save data in webhook
        webhook_data    =   WebhookData(
                webhook_data   =   payload,
                is_delete       =   0,
                created_at      =   timezone.now()
            )

        webhook_data.save()
        
    # except ValueError:
    #     return HttpResponseBadRequest("Invalid JSON payload")
    except:
        pass

    return JsonResponse({
                            "success"       :   1,
                            "message"       :   "paypal information received ",
                    })  



 









@api_view(['POST'])
    # Save the customer ID for later use
def save_customer_id(customer_id):
        # You can implement your own logic to save the customer ID, such as storing it in a database or file
        # For demonstration purposes, we'll simply print it here


        # Usage
        customer_id = create_customer()

        pass 
        if customer_id:
            save_customer_id(customer_id)



@api_view(['POST'])

def create_paypal_token(request):
    token = request.headers.get('Authorization')
    user_token = token.replace("Bearer", "").strip()  # Remove leading/trailing spaces
    
    check_user = token_verification(user_token)
    
    if check_user is None:
        return JsonResponse({
            "success": 2,
            "message": "Unauthorized User",
        })
    else:

        url             =   'https://api-m.sandbox.paypal.com/v1/oauth2/token'
        headers         =   {'Accept': 'application/json', 'Accept-Language': 'en_US'}
        data            =   {'grant_type': 'client_credentials'}
        auth            =   (client_id, client_secret)
        response        =   requests.post(url, headers=headers, data=data, auth=auth)

        access_token    =   response.json()['access_token']
        paypal_req_id    =  request.data.get('paypal_req_id') # random text 

        login_customer = check_user['session_user']
        user = Registration.objects.get(user_id=login_customer)

            #  payapl authentication
        headers = {
            'Content-Type': 'application/json',
            'PayPal-Request-Id': paypal_req_id,  # change id on each request
            'Authorization': 'Bearer '+ access_token,
        }


        data={
            "payment_source": {
                "card": {
                    "number": "4111111111111111",
                    "expiry": "2027-02",
                    "name": "Firstname Lastname",
                    "billing_address": {
                        "address_line_1": "2211 N First Street",
                        "address_line_2": "17.3.160",
                        "admin_area_1": "CA",
                        "admin_area_2": "San Jose",
                        "postal_code": "95131",
                        "country_code": "US"
                    },
                    
                }
            }
        }
        response = requests.post('https://api-m.sandbox.paypal.com/v3/vault/setup-tokens', headers=headers, json=data)

        resp_data = json.loads(response.text)

        try:
            if resp_data["status"] == "COMPLETED":
                
                valut_id = resp_data['payment_source']["card"]["attributes"]["vault"]["id"]

                cust_id  = resp_data['payment_source']["card"]["attributes"]["vault"]["customer"]["id"]

                paypal_data = PaypalInfo(
                            paypal_user     =   user,
                            paypal_valut_id =   valut_id,
                            paypal_response =   resp_data,
                            paypal_cust_id  =   cust_id,
                            is_delete       =   0,
                            created_at      =    timezone.now()  
                )
                paypal_data.save()

                return JsonResponse({
                            "success"       :   1,
                            "message"       :   "payment success",
                            "data"          :   resp_data

                    })  
        except:
            pass           
        else:
                
            return JsonResponse({
                    "success"       :   0,
                    "message"       :   "Something went wrong",
                        
            })
        return JsonResponse({
                        "success"       :   0,
                        "message"       :   "Something went wrong",
                            
                })


